version: '3.8'

services:
  database:
    container_name: rpi-iot-thermometer-database
    image: postgres:14.3-alpine3.15
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data

  mqtt:
    container_name: rpi-iot-thermometer-mqtt
    image: eclipse-mosquitto:2.0.14
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ${PWD}/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt:/mosquitto:rw

volumes:
  database:
  mqtt:
