version: '3.8'

services:
  server:
    container_name: rpi-iot-thermometer-server
    build:
      context: ./packages/server
    ports:
      - 3001:3001
    restart: always
    links:
      - database
      - mqtt
    environment:
      HOST: "0.0.0.0"
      PORT: 3001
      MQTT_BROKER_HOST: mqtt
      MQTT_BROKER_PORT: 1883
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: rpi_iot_thermometer
    depends_on:
      - database
      - mqtt

  frontend:
    container_name: rpi-iot-thermometer-frontend
    build:
      context: ./packages/frontend
    ports:
      - 3002:3001
    restart: always
    links:
      - server
    environment:
      API_URL: http://server:3001
      API_URL_FOR_BROWSER: http://pi4.home.lan:3001
    depends_on:
      - server

  database:
    container_name: rpi-iot-thermometer-database
    image: postgres:14.3-alpine3.15
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    restart: always
    volumes:
      - database:/var/lib/postgresql/data

  mqtt:
    container_name: rpi-iot-thermometer-mqtt
    image: eclipse-mosquitto:2.0.14
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
    volumes:
      - ${PWD}/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - mqtt:/mosquitto:rw

volumes:
  database:
  mqtt:

networks:
  net:
