name: Tests

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Resolve dependencies
        run: yarn

      - name: Run tests
        run: yarn test
